import fs from "node:fs";
import path from "node:path";
const [dir, tag] = process.argv.slice(2);
if (!dir || !/^v\d+\.\d+\.\d+$/.test(tag || "")) throw new Error("Expected package directory and stable tag vX.Y.Z");
const manifestPath = path.join(dir, "plugin.json");
const scriptPath = path.join(dir, "index.js");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
if (manifest.version !== tag.slice(1)) throw new Error("Manifest version does not match upstream tag");
let source = fs.readFileSync(scriptPath, "utf8");
const contextPattern = /(e\[a\(506\)\]\(Lgx,\{)isFree:r,isNotFree:c,isPro:u,isVip:b,isPermanent:s,levelLabel:o,levelIcon:d,computedLevel:l(\}\))/g;
let contextMatches = 0;
source = source.replace(contextPattern, (_all, start, end) => { contextMatches++; return start + "isFree:ux(()=>!1),isNotFree:ux(()=>!0),isPro:u,isVip:b,isPermanent:s,levelLabel:o,levelIcon:d,computedLevel:l" + end; });
if (contextMatches !== 1) throw new Error("Expected one shared context; refusing to publish");
const expression = "return!i||p[E(539)](t[E(532)].lv,p[E(586)](Number,i))";
if (source.split(expression).length - 1 !== 1) throw new Error("Expected one existing level decision; refusing to publish");
source = source.replace(expression, "return!0");
fs.writeFileSync(scriptPath, source, "utf8");
console.log("Patch applied: shared access decision updated; original identity refs and computed-level registration retained.");
